import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header
          alpha="en-US"
          kicker="Saving your money since 2024"
          title={
            <>
              <span className="text-primary">20.000+</span> Coupons{' '}
              <span className="text-primary">1.000+</span> Stores
            </>
          }
          subtitle="Get your Coupon today and save yourself up to 50% of your money"
        />
        {children}
      </body>
    </html>
  );
}
