import type { ReactNode } from 'react';
import { Inter } from 'next/font/google';
import './globals.css';
import { Metadata } from 'next';
import { IsClientCtxProvider } from '@/helpers/isClientCtx';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Trusted Coupons',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests" />
      </Head>
      <body suppressHydrationWarning={true} className={inter.className}>
        <IsClientCtxProvider>{children}</IsClientCtxProvider>
      </body>
    </html>
  );
}
